In [1]:
# -*- coding: utf-8 -*- 

import numpy 

from konlpy.tag import Okt
okt = Okt()

from konlpy.tag import Mecab
mecab = Mecab()

from khaiii import KhaiiiApi
api = KhaiiiApi()

import pandas as pd

n = input("typing the number of tsv file: ")

dataset = pd.read_csv("/Users/bobopack/Downloads/CS489-Team-14-repository-main 3/crawling_output/crawling_output_{0}.tsv".format(n)
, delimiter='\t', names = ['제목/댓글번호','기사작성시간/댓글본문','기사본문/좋아요','none/싫어요','none/답글수'])

datatable = dataset.values.tolist()


title = datatable[0][0]
article = datatable[0][2]
art = article.split("▶")
if len(art) > 1:
    icle = art[:-3]
    s = ""
    for t in icle:
        s += t
    article = s

comments = []
replys = []

comList = dataset['기사작성시간/댓글본문'].tolist()[0:]


for i in range(1,len(datatable)):
    line = datatable[i]
    if datatable[i-1][0] == datatable[i][0]:  #대댓글일때 (라인넘버, 대댓글본문)
        replys.append(line[:2])
    else:
        comments.append(line[:2]+line[4:])  #댓글일때 (라인넘버, 댓글본문, 답글갯수)

typing the number of tsv file: 0


In [2]:
dataset

제목/댓글번호  \
0    [종합] 코로나3차 대유행 공포…신규확진 569명 이틀째 500명대   
1                                        1   
2                                        1   
3                                        1   
4                                        1   
..                                     ...   
131                                    100   
132                                    101   
133                                    102   
134                                    102   
135                                    102   

                                           기사작성시간/댓글본문  \
0                                  2020.11.27. 오전 9:50   
1                  무엇 때문 인지 , 이번 대통령님의 임기가 참 길게 느껴집니다.   
2                    왜냐하면 저번 대통령은 임기를 다 못 채우셔서 짧게 늦겨진듯   
3                                       님은 니미. 새끼도 아까움   
4                                         당신이 대통령 해보지.   
..                                                 ...   
131  코로나 확진자랑 무조건 최대한 멀리 떨어지세요. 코로나바이러스 완치없습니다. 돌연변...   
132  어디가서 우리나라 시민의식 수준급이라고 하지말자.. 그렇게 모이지말라고 했는데 굳이...   
133            K방역 화이팅   문재인  민주당에 감사드립니다.코로나 대응 잘  해서   
134                              와 이새ㄱㅣ다른기사에 댓글단거 소름이네   
135                                          욕 처먹고 싶냐?   

                                              기사본문/좋아요  none/싫어요  none/답글수  
0    국내 신종 코로나바이러스 감염증(코로나19)의 '3차 대유행'이 본격적으로 진행되면...       NaN       NaN  
1                                    8.977279923499918  5.459432      11.0  
2                                    4.321928094887363  1.000000       NaN  
3                                                    0  0.000000       NaN  
4                                                  2.0  4.247928       NaN  
..                                                 ...       ...       ...  
131                                                  0  0.000000       0.0  
132                                                  0  0.000000       0.0  
133                                  2.807354922057604  4.700440       2.0  
134                                                  0  0.000000       NaN  
135                                                  0  0.000000       NaN  

[136 rows x 5 columns]

In [ ]:
#okt
# def get_morphs(text):
#     tags = okt.pos(text, norm='True', stem='True')
#     l = [] 
#     for words in tags:  
#         l.append(words[0])
#     return l

# def get_nouns(text):
#     key = ["Noun"] 
#     tags = okt.pos(text, norm='True', stem='True')
#     l = [] 
#     for words in tags:  
#         if words[1] in key:
#             l.append(words[0])
#     return l
    
# def num_pos(text):
#     tags = okt.pos(text, norm='True', stem='True')
#     return len(tags)

In [3]:
#mecab
def get_morphs(text):
    tags = mecab.pos(text)
    l = [] 
    for words in tags:  
        l.append(words[0])
    return l

def get_nouns(text):
# 일반명사,고유명사
    key = ["NNG", "NNP"] 
    tags = mecab.pos(text)
    l = [] 
    for words in tags:  
        if words[1] in key:
            l.append(words[0])
    return l
    
def num_pos(text):
    tags = mecab.pos(text)
    return len(tags)



In [ ]:
# #khaiii

# # 일반명사,고유명사
# key = ["NNG", "NNP"] 

# for reply in cat_list:
    
#     morphs = []
#     for word in api.analyze(reply):
#         for morph in word.morphs:
#             morphs.append((morph.lex, morph.tag))
#     tags = morphs

#     print(tags)
# #     l = [] 
# #     for words in tags:  
# #         if words[1] in key:
# #             l.append(words)
# #     print(l)
    

In [4]:
# 명사개수
def num_naive(text):
    nouns = get_nouns(text)
    return len(nouns)

# 명사종류개수
def num_only(text):
    nouns = get_nouns(text)
    return len(set(nouns))

# 본문포함된 명사개수
def num_naive_article(article, text):
    article_nouns = get_nouns(article)
    nouns = get_nouns(text)
    real_nouns = []
    for noun in nouns:
        if noun in article_nouns:
            real_nouns.append(noun)
    return len(real_nouns)

# 본문포함된 명사종류개수
def num_only_article(article, text):
    article_nouns = set(get_nouns(article))
    nouns = set(get_nouns(text))
    inter = nouns.intersection(article_nouns)
    return len(inter)



# processed comments and replys
proc_comments = []
# proc_replys = []

for comment in comments:
    content = comment[1]
    processing = comment + [num_pos(content), 
                            num_naive(content), 
                            num_only(content), 
                            num_naive_article(article, content), 
                            num_only_article(article, content)]
    proc_comments.append(processing)
# for reply in replys:
#     content = reply[1]
#     processing = comment + [num_pos(content), num_naive(content), num_only(content), num_naive_article(article, content), num_only_article(article, content)]
#     proc_replys.append(processing)

In [5]:
# Jaccard Similarity
def jac_sim(article, text):
    article = set(get_morphs(article))
    comment = set(get_morphs(text))
    inter = comment.intersection(article)
    uni = comment.union(article)
    return len(inter)/len(uni)

def nonset_jac_sim(article, text):
    article = get_morphs(article)
    comments = get_morphs(text)
    inter = []
    for comment in comments:
        if comment in article:
            inter.append(comment)
    uni = set(comments).union(set(article))
    return len(inter)/len(uni)

def noun_jac_sim(article, text):
    article_nouns = set(get_nouns(article))
    nouns = set(get_nouns(text))
    inter = nouns.intersection(article_nouns)
    uni = nouns.union(article_nouns)
    return len(inter)/len(uni)

def nonset_noun_jac_sim(article, text):
    article_nouns = get_nouns(article)
    nouns = get_nouns(text)
    real_nouns = []
    for noun in nouns:
        if noun in article_nouns:
            real_nouns.append(noun)
    uni = set(nouns).union(set(article_nouns))
    return len(real_nouns)/len(uni)

    
# revised rated comments and replys    
rated_comments = []
# rated_replys = []

for comment in comments:
    content = comment[1]
#     n = num_pos(content)
    rating = comment + [num_pos(content),
                        num_naive_article(article, content) / (num_naive(content)+1), 
                        num_only_article(article, content) / (num_only(content)+1), 
                        jac_sim(article, content), 
                        nonset_jac_sim(article, content), 
                        noun_jac_sim(article, content), 
                        nonset_noun_jac_sim(article, content)]
    rated_comments.append(rating)

    
    
# for reply in replys:
#     content = reply[1]
# #     n = num_pos(content)
#     rating = comment + [num_naive_article(article, content)/(num_naive(content)+1), 
#                         num_only_article(article, content)/(num_only(content)+1), 
#                         jac_sim(article, content), 
#                         nonset_jac_sim(article, content), 
#                         noun_jac_sim(article, content), 
#                         nonset_noun_jac_sim(article, content)]
#     rated_replys.append(rating)
    
 

In [6]:
   
# part for sklearn, similarity

from sklearn.feature_extraction.text import TfidfVectorizer

def tfid_vectorize(article, comment):
    sent = (article, comment)
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(sent) #문장 벡터화 진행
    idf = tfidf_vectorizer.idf_
    #print(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))
    return tfidf_matrix

#Cosine_similarity

from sklearn.metrics.pairwise import cosine_similarity
def cos_sim(matrix):
    sim = cosine_similarity(matrix[0:1], matrix[1:2]) #첫번째와 두번째 문장 비교
    #array([[0.113]])
    return sim[0][0]

#Euclidean Distance or L2-Distance

from sklearn.metrics.pairwise import euclidean_distances
def euc_dis(matrix):
    sim = euclidean_distances(matrix[0:1], matrix[1:2])
    #array([[1.331]])
    return sim[0][0]

#L1-Normalization

import numpy as np
def l1_normalize(v):
    norm = np.sum(v)
    return v / norm
def nor_euc_dis(matrix):
    tfidf_norm_l1 = l1_normalize(matrix)
    sim = euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])
    # array([[0.212]])
    return sim[0][0]

#Manhattan Similarity or  L1-Distance

from sklearn.metrics.pairwise import manhattan_distances
def manh_dis(matrix):
    sim = manhattan_distances(matrix[0:1], matrix[1:2])
    #array([[0.857]])
    return sim[0][0]
def nor_manh_dis(matrix):
    tfidf_norm_l1 = l1_normalize(matrix)
    sim = manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])
    #array([[0.857]])
    return sim[0][0]

# similarity commnets

similarity_comments = []

for comment in comments:
    content = comment[1]
    tfidf_matrix = tfid_vectorize(article, content)
    #tfidf_matrix = tfid_vectorize(summary, content)
    similarity = comment + [cos_sim(tfidf_matrix), euc_dis(tfidf_matrix), nor_euc_dis(tfidf_matrix), manh_dis(tfidf_matrix), nor_manh_dis(tfidf_matrix)]
    similarity_comments.append(similarity)
    

In [7]:
print("Entire num of commnets is: {0}\n".format(len(comments)))
print(article)

Entire num of commnets is: 102

국내 신종 코로나바이러스 감염증(코로나19)의 '3차 대유행'이 본격적으로 진행되면서 27일 신규 확진자 수는 또다시 500명대를 나타냈다.  전날(583명)에 이어 이틀 연속 500명대를 기록한 것이다.  이틀 연속 500명 이상 확진자가 나온 것은 대구·경북 중심의 '1차 대유행'이 한창이던 3월 초 이후 약 9개월 만이다.  정부와 감염병 전문가들은 지금의 확산세를 꺾지 못하면 하루 1000명 이상 확진자가 나올 수도 있을 것으로 내다보고 있다.  중앙방역대책본부는 이날 0시 기준으로 코로나19 신규 확진자가 569명 늘어 누적 3만2887명이라고 밝혔다. 전날(583명)과 비교하면 14명 줄었다.  방역당국이 3차 유행을 공식화한 가운데 국내 코로나19 확진자는 빠른 속도로 늘고 있다.  이달 들어 일별 신규 확진자 수는 124명→97명→75명→118명→125명→145명→89명→143명→126명→100명→146명→143명→191명→205명→208명→222명→230명→313명→343명→363명→386명→330명→271명→349명→382명→583명→569명 등이다. 지난 8일부터 20일 연속 세 자릿수를 이어간 가운데 300명을 넘긴 날은 9차례고, 500명대는 2차례다.  신규 확진자 569명의 감염경로를 보면 지역발생이 525명, 해외유입이 44명이다.  신규 확진자가 나온 지역을 보면 서울 204명, 경기 112명, 인천 21명 등 337명이다. 수도권 지역발생 확진자는 전날(402명)보다 65명 줄었지만, 300명대를 기록하며 전체 지역발생의 64.2%를 차지했다.  비수도권의 경우 경남이 38명으로 가장 많고 이어 충남 31명, 전북·부산 각 24명, 충북 19명, 광주 13명, 전남 10명, 강원 8명, 울산 7명, 대전 5명, 세종·경북·제주 각 3명이다.  해외유입 확진자는 44명으로, 전날(30명)보다 14명 늘었다.  한편 사망자는 전날보다 1명 늘어 누적 516명이 됐다. 국내 평

In [8]:
df0 = pd.DataFrame(comments, columns=['댓글번호','댓글본문','답글수'])
df0.head(10)

댓글번호                                               댓글본문   답글수
0    1                무엇 때문 인지 , 이번 대통령님의 임기가 참 길게 느껴집니다.  11.0
1    2  민노총집회후 늘었는데 민노총관련확진자 분류하여 발표안하는이정권 이해가안된다 정부는 ...   2.0
2    3                                 3단계로 해라 진짜 스트레스받는다   6.0
3    4  외식쿠폰.숙박쿠폰등..공무원들 회식.모임등.. 무능한 정부. 맨날 나라 분열만 조장...   4.0
4    5  문재인  진짜 아낌없이 주는 나무네 중국은 혈장검사 검사2회 실시 조치하는데 우리나...   1.0
5    6  곧 1000명대가 코앞인데 추미애는 검란이나 일으키고 문재인은 중국신하에게 굽신거리...   0.0
6    7  메르스사태때 문재인 대통령은 뭐라했나?무능한 정권이라고 안했나?그렇케 비판하던 전정...   0.0
7    8  대구때는 진짜 사람이 없을정도..번화가도 횡햇었는데..서울 경기 수도권 번화가 나가...   1.0
8    9  다들 K방역이라 부르시던데  이제는 T(대구)방역이라 부르시는게 정답입니다.  @@...   0.0
9   10                              민주노총 집회관련 확진자 언급은 없네.   0.0

In [ ]:
# just for test
df0 = pd.DataFrame(comments)
new_df0 = df0.head(4).T
new_df0.columns = ['a','b','c','d']
new_df0

In [9]:
df1 = pd.DataFrame(proc_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                             '명사개수','명사종류개수',
                                             '본문명사개수','본문명사종류개수'])

new_df1 = df1.sort_values(by='본문명사개수', ascending=False)

new_df1.head(10)
#new_df1
#df1

댓글번호                                               댓글내용  답글수  pos길이  명사개수  \
97   98  서울수도권은 대체  왜그러는지 참 이해가안되네..지금은법적으로 마스크도하고 방역지침...  0.0     88    19   
27   28  급한대로 서울 경기 두 지역만 집중관리하면 안 됩니까? 인천도 확진자들 보면 다 서...  0.0     32    11   
99  100  코로나 확진자랑 무조건 최대한 멀리 떨어지세요. 코로나바이러스 완치없습니다. 돌연변...  0.0     78    34   
22   23  천안사는데요 두정동이라는 먹자골목이있습니다. 어제밤이에갔는데 코로나가 하루확진자가 ...  0.0    102    24   
6     7  메르스사태때 문재인 대통령은 뭐라했나?무능한 정권이라고 안했나?그렇케 비판하던 전정...  0.0    166    48   
8     9  다들 K방역이라 부르시던데  이제는 T(대구)방역이라 부르시는게 정답입니다.  @@...  0.0     33     9   
10   11  결국 사태의 원인은 행정부에서 책임을 지는 것이 맞는 겁니다 . 최종 책임의 주체는...  1.0    152    36   
38   39  이번 3차 대유행은 할로윈의 영향같다. 시기도 할로윈 끝나고 몇주 안지났고, 젊은 ...  0.0     54    13   
14   15  오잉 오늘 대구 한명도 안나왔네 ㅋㅋㅋ 이제 서울 경기가 대구보다 더많이 나오네 음...  0.0     23     6   
7     8  대구때는 진짜 사람이 없을정도..번화가도 횡햇었는데..서울 경기 수도권 번화가 나가...  1.0     49    13   

    명사종류개수  본문명사개수  본문명사종류개수  
97      17      10         8  
27       8       8         5  
99      30       7         5  
22      24       5         5  
6       36       5         4  
8        7       5         3  
10      26       5         2  
38      11       4         4  
14       5       4         3  
7       12       4         4

In [10]:
df2 = pd.DataFrame(rated_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                              '본문/전체명사','본문/전체명사종류', 
                                              '자카드','nonset자카드',
                                              '자카드명사','nonset자카드명사'])

new_df2 = df2.sort_values(by='본문/전체명사', ascending=False)

new_df2.head(10)

#new_df2

댓글번호                                               댓글내용  답글수  pos길이  \
27   28  급한대로 서울 경기 두 지역만 집중관리하면 안 됩니까? 인천도 확진자들 보면 다 서...  0.0     32   
77   78                                        해외 유입좀 막아줘요  0.0      6   
14   15  오잉 오늘 대구 한명도 안나왔네 ㅋㅋㅋ 이제 서울 경기가 대구보다 더많이 나오네 음...  0.0     23   
97   98  서울수도권은 대체  왜그러는지 참 이해가안되네..지금은법적으로 마스크도하고 방역지침...  0.0     88   
8     9  다들 K방역이라 부르시던데  이제는 T(대구)방역이라 부르시는게 정답입니다.  @@...  0.0     33   
57   58                          대구 봉쇄하자는 사람들 어디? 대구만 0명이네  0.0     14   
56   57                          대구 봉쇄하자는 사람들 어디? 대구만 0명이네  0.0     14   
80   81                     삼성다니는데 코로나 확진자 생겼다 3단계로 올려라 ㅡㅡ  0.0     13   
16   17  적어도 수도권은 2.5 단계 이상 격상해야 하고 타지역도 2단계로는 올려야 맞다고 ...  0.0     27   
78   79  정부 이늠들 감염학과 의사들 말 들어라~지금은 전국적으로 다 퍼졌기때문에 예전이랑 ...  0.0     41   

     본문/전체명사  본문/전체명사종류       자카드  nonset자카드     자카드명사  nonset자카드명사  
27  0.666667   0.555556  0.064655   0.086207  0.062500     0.100000  
77  0.666667   0.666667  0.008929   0.008929  0.025974     0.025974  
14  0.571429   0.500000  0.038793   0.043103  0.037975     0.050633  
97  0.500000   0.444444  0.122530   0.193676  0.093023     0.116279  
8   0.500000   0.375000  0.046809   0.068085  0.037037     0.061728  
57  0.400000   0.250000  0.030973   0.035398  0.012658     0.025316  
56  0.400000   0.250000  0.030973   0.035398  0.012658     0.025316  
80  0.400000   0.400000  0.026432   0.026432  0.025316     0.025316  
16  0.375000   0.428571  0.056522   0.069565  0.037500     0.037500  
78  0.333333   0.333333  0.066667   0.079167  0.047619     0.047619

In [ ]:
df2 = pd.DataFrame(rated_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                              '본문/전체명사','본문/전체명사종류', 
                                              '자카드','nonset자카드',
                                              '자카드명사','nonset자카드명사'])

new_df2 = df2.sort_values(by='본문/전체명사종류', ascending=False)

new_df2.head(10)

#new_df2

In [ ]:
df2 = pd.DataFrame(rated_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                              '본문/전체명사','본문/전체명사종류', 
                                              '자카드','nonset자카드',
                                              '자카드명사','nonset자카드명사'])

new_df2 = df2.sort_values(by='자카드', ascending=False)

new_df2.head(10)

#new_df2

In [11]:
df2 = pd.DataFrame(rated_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                              '본문/전체명사','본문/전체명사종류', 
                                              '자카드','nonset자카드',
                                              '자카드명사','nonset자카드명사'])

new_df2 = df2.sort_values(by='nonset자카드', ascending=False)

new_df2.head(10)

#new_df2

댓글번호                                               댓글내용  답글수  pos길이  \
10    11  결국 사태의 원인은 행정부에서 책임을 지는 것이 맞는 겁니다 . 최종 책임의 주체는...  1.0    152   
6      7  메르스사태때 문재인 대통령은 뭐라했나?무능한 정권이라고 안했나?그렇케 비판하던 전정...  0.0    166   
97    98  서울수도권은 대체  왜그러는지 참 이해가안되네..지금은법적으로 마스크도하고 방역지침...  0.0     88   
22    23  천안사는데요 두정동이라는 먹자골목이있습니다. 어제밤이에갔는데 코로나가 하루확진자가 ...  0.0    102   
23    24  정부는 코로나 끝날까봐 더 두려워하는 것 같다 국민들 목숨이 달렸는데 백신 확보도 ...  0.0     94   
99   100  코로나 확진자랑 무조건 최대한 멀리 떨어지세요. 코로나바이러스 완치없습니다. 돌연변...  0.0     78   
38    39  이번 3차 대유행은 할로윈의 영향같다. 시기도 할로윈 끝나고 몇주 안지났고, 젊은 ...  0.0     54   
84    85  진심 집회 안막고 검토 몇주하고 등교 유지에 거리두기 강화 안해서 그럼 뭔 200명...  0.0    107   
85    86  짱깨들 막지도 않고 의료진의 희생과 국민들이 마스크 열심히 쓰면서 노력해서  획진자...  0.0     77   
100  101  어디가서 우리나라 시민의식 수준급이라고 하지말자.. 그렇게 모이지말라고 했는데 굳이...  0.0     63   

      본문/전체명사  본문/전체명사종류       자카드  nonset자카드     자카드명사  nonset자카드명사  
10   0.135135   0.074074  0.092593   0.318519  0.019802     0.049505  
6    0.102041   0.108108  0.110727   0.259516  0.036697     0.045872  
97   0.500000   0.444444  0.122530   0.193676  0.093023     0.116279  
22   0.200000   0.200000  0.087273   0.163636  0.052083     0.052083  
23   0.125000   0.096774  0.088561   0.147601  0.028846     0.038462  
99   0.200000   0.161290  0.076923   0.138462  0.049020     0.068627  
38   0.285714   0.333333  0.096234   0.125523  0.047619     0.047619  
84   0.000000   0.000000  0.050360   0.122302  0.000000     0.000000  
85   0.095238   0.095238  0.060150   0.109023  0.021053     0.021053  
100  0.071429   0.083333  0.059761   0.103586  0.011494     0.011494

In [ ]:
df2 = pd.DataFrame(rated_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                              '본문/전체명사','본문/전체명사종류', 
                                              '자카드','nonset자카드',
                                              '자카드명사','nonset자카드명사'])

new_df2 = df2.sort_values(by='자카드명사', ascending=False)

new_df2.head(10)

#new_df2

In [ ]:
df2 = pd.DataFrame(rated_comments, columns = ['댓글번호','댓글내용','답글수','pos길이',
                                              '본문/전체명사','본문/전체명사종류', 
                                              '자카드','nonset자카드',
                                              '자카드명사','nonset자카드명사'])

new_df2 = df2.sort_values(by='nonset자카드명사', ascending=False)

new_df2.head(10)

#new_df2

In [12]:
df3 = pd.DataFrame(similarity_comments, columns = ['댓글번호','댓글내용','답글수',
                                                   '코사인유사도',
                                                   '유클리디언','norm유클',
                                                   '맨해튼','norm맨해'])

new_df3 = df3.sort_values(by='코사인유사도', ascending=False)

new_df3
#df3

new_df3.head(10)

댓글번호                                               댓글내용  답글수    코사인유사도  \
27   28  급한대로 서울 경기 두 지역만 집중관리하면 안 됩니까? 인천도 확진자들 보면 다 서...  0.0  0.069333   
15   16  보수꼴통 집회 관련 확진자는 집요하게 통계내더만 어째 민노총 집회 확진자는 일언반구...  1.0  0.044409   
31   32                       민노총집회 허가하는이정부하곤 민노총 확진자 발표해라  0.0  0.039173   
9    10                              민주노총 집회관련 확진자 언급은 없네.  0.0  0.039173   
65   66  지금까지  매주 수만명 관광객이 와도 동선겹친자들 음성판정받고 나름 청정지역이었던 ...  0.0  0.037134   
45   46                          이와중에 대구만 확진자 없음~~대단한 시민의식  0.0  0.035438   
26   27                       민노총   집회 창가자  확진자  몇명인지  말해라  0.0  0.035438   
80   81                     삼성다니는데 코로나 확진자 생겼다 3단계로 올려라 ㅡㅡ  0.0  0.032601   
72   73                                     3차 펜데믹 온듯..가즈하  0.0  0.029497   
23   24  정부는 코로나 끝날까봐 더 두려워하는 것 같다 국민들 목숨이 달렸는데 백신 확보도 ...  0.0  0.028107   

       유클리디언    norm유클        맨해튼    norm맨해  
27  1.364307  0.088058  14.945484  0.964640  
15  1.382455  0.091202  14.924452  0.984579  
31  1.386237  0.096754  14.093729  0.983685  
9   1.386237  0.096754  14.093729  0.983685  
65  1.387707  0.086920  15.574568  0.975526  
45  1.388929  0.095512  14.308257  0.983926  
26  1.388929  0.095512  14.308257  0.983926  
80  1.390970  0.094372  14.505449  0.984141  
72  1.393200  0.099081  13.906026  0.988958  
23  1.394197  0.073689  18.479902  0.976737

In [ ]:
df3 = pd.DataFrame(similarity_comments, columns = ['댓글번호','댓글내용','답글수',
                                                   '코사인유사도',
                                                   '유클리디언','norm유클',
                                                   '맨해튼','norm맨해'])

new_df3 = df3.sort_values(by='유클리디언', ascending=True)

new_df3
#df3

new_df3.head(10)

In [13]:
df3 = pd.DataFrame(similarity_comments, columns = ['댓글번호','댓글내용','답글수',
                                                   '코사인유사도',
                                                   '유클리디언','norm유클',
                                                   '맨해튼','norm맨해'])

new_df3 = df3.sort_values(by='norm유클', ascending=True)

new_df3
#df3

new_df3.head(10)

댓글번호                                               댓글내용  답글수    코사인유사도  \
10   11  결국 사태의 원인은 행정부에서 책임을 지는 것이 맞는 겁니다 . 최종 책임의 주체는...  1.0  0.003171   
6     7  메르스사태때 문재인 대통령은 뭐라했나?무능한 정권이라고 안했나?그렇케 비판하던 전정...  0.0  0.010307   
23   24  정부는 코로나 끝날까봐 더 두려워하는 것 같다 국민들 목숨이 달렸는데 백신 확보도 ...  0.0  0.028107   
84   85  진심 집회 안막고 검토 몇주하고 등교 유지에 거리두기 강화 안해서 그럼 뭔 200명...  0.0  0.000000   
85   86  짱깨들 막지도 않고 의료진의 희생과 국민들이 마스크 열심히 쓰면서 노력해서  획진자...  0.0  0.000000   
22   23  천안사는데요 두정동이라는 먹자골목이있습니다. 어제밤이에갔는데 코로나가 하루확진자가 ...  0.0  0.000000   
99  100  코로나 확진자랑 무조건 최대한 멀리 떨어지세요. 코로나바이러스 완치없습니다. 돌연변...  0.0  0.014986   
24   25  해외도 안막고 중국은 우리나라 사람한테 혈장검사 검사2회 실시하는데 우리는 중국인 ...  0.0  0.004909   
4     5  문재인  진짜 아낌없이 주는 나무네 중국은 혈장검사 검사2회 실시 조치하는데 우리나...  1.0  0.005566   
19   20  3단계로 격상시켜 코로나확산을 조금이라도 막는 노력이 필요합니다.확진자가 많아지면 ...  0.0  0.020875   

       유클리디언    norm유클        맨해튼    norm맨해  
10  1.411969  0.070279  20.013437  0.996145  
6   1.406907  0.073400  18.934907  0.987859  
23  1.394197  0.073689  18.479902  0.976737  
84  1.414214  0.076633  18.454465  1.000000  
85  1.414214  0.077535  18.239622  1.000000  
22  1.414214  0.078979  17.906160  1.000000  
99  1.403577  0.079341  17.457704  0.986845  
24  1.410738  0.081256  17.284174  0.995539  
4   1.410272  0.082665  16.982718  0.995460  
19  1.399375  0.083377  16.517191  0.984120

In [ ]:
df3 = pd.DataFrame(similarity_comments, columns = ['댓글번호','댓글내용','답글수',
                                                   '코사인유사도',
                                                   '유클리디언','norm유클',
                                                   '맨해튼','norm맨해'])

new_df3 = df3.sort_values(by='맨해튼', ascending=True)

new_df3
#df3

new_df3.head(10)

In [ ]:
df3 = pd.DataFrame(similarity_comments, columns = ['댓글번호','댓글내용','답글수',
                                                   '코사인유사도',
                                                   '유클리디언','norm유클',
                                                   '맨해튼','norm맨해'])

new_df3 = df3.sort_values(by='norm맨해', ascending=True)

new_df3
#df3

new_df3.head(10)